title: Ryoma Otsuka
logo: /images/icons/dokudami_gorilla_lightblue_square.png
description: A post-doc researcher.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
markdown: GFM # for GitHub pages
# markdown: kramdown # for local environment debugging