theme: minima
# theme: jekyll-theme-minimal
title: Ryoma Otsuka
# description: TBA
# logo: /images/dokudami_gorilla_blue.png
show_downloads: false

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages
