title: Ryoma Otsuka
markdown: GFM

# description:
# baseurl: "/"
# url: "https://ryoma-otsuka.github.io"
# 
# markdown: kramdown
# kramdown:
#   input: GFM  # Enable GitHub Flavored Markdown

# defaults:
#   - scope:
#       path: ""
#     values:
#       custom_css: "/assets/css/style.css"